openapi: 3.0.0

info:
  version: 1.0.0
  title: SensorLab VideoWall API
  description:  |
    A simple API to control the SensorLab VideoWall from a remote website

    **MVP features are:**
    - As a user, I want to see all the animations available
    - As a user, I want to select and play an animation
    - As a user, I want to stop the current animation

    **Nice To Have feature are:**
    - As a user, I want to pick color(s) as parameter for an animation
    - As a user, I want to pass a sentence as a parameter for the Alphabet animation
    - As a user, I want to upload an image to use for the Image animation
    - As a user, I want to upload a video to use for the Video animation
    - As a user, I want to define a looping queue of animations
    - ...



servers:
  - url: http://localhost:8080

tags:
  - name: Animations
    description: All calls related to manage animations

components:
  schemas:
    ColorParameter:
      type: object
      required: [id, name, type]
      properties:
        id:
          type: integer
          description: "Id of the color parameters arranged in the order as they will be processed by the animation"
        name:
          type: string
        type:
          type: string
          enum:
            - color

    StringParameter:
      type: object
      required: [id, name, type]
      properties:
        id:
          type: integer
          description: "Id of the string parameters arranged in the order as they will be processed by the animation"
        name:
          type: string
        type:
          type: string
          enum:
            - string

    ValueIntegerParameter:
      type: object
      required: [id, name, type]
      properties:
        id:
          type: integer
          description: "Id of the value integer parameters arranged in the order as they will be processed by the animation"
        name:
          type: string
        min:
          type: integer
        max:
          type: integer
        type:
          type: string
          enum:
            - integer

    AnimationParameter:
      oneOf:
        - $ref: '#/components/schemas/ColorParameter'
        - $ref: '#/components/schemas/StringParameter'
        - $ref: '#/components/schemas/ValueIntegerParameter'

    Animation:
      type: object
      required: [id, name, active]
      properties:
        id:
          type: string
          description: "Unique ID for animation"
        name:
          type: string
          description: "Animation title"
        active:
          type: boolean
          description: "True if it's the currently played animation"
        parameters:
          type: array
          description: "Parameters available for this animation"
          items:
            $ref: '#/components/schemas/AnimationParameter'

  responses:
    Error400Response:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            required: [code, message]
            properties:
              code:
                type: integer
                example: 400
              message:
                type: string
                example: "Missing or invalid parameter(s): 'foo', 'bar', 'baz'"

    Error404Response:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            required: [code, message]
            properties:
              code:
                type: integer
                example: 404
              message:
                type: string
                example: "Resource not found"

    Error500Response:
      description: Unexpected server error
      content:
        application/json:
          schema:
            type: object
            required: [code, message]
            properties:
              code:
                type: integer
                example: 500
              message:
                type: string
                example: "The server failed to respond to the request"

  parameters:
    animationIdParameter_path:
      in: path
      name: animationId
      description: Unique id of the animation
      required: true
      schema:
        type: string

    animationColorsParameter_query:
      in: query
      name: colors
      description: List of colors to use for the animation, ordered by Id
      required: false
      schema:
        type: array
        items:
          type: string

    animationStringsParameter_query:
      in: query
      name: strings
      description: List of strings to use for the animation, ordered by Id
      required: false
      schema:
        type: array
        items:
          type: string

    animationValuesIntegerParameter_query:
      in: query
      name: valueIntegers
      description: List of integer values to use for the animation, ordered by Id
      required: false
      schema:
        type: array
        items:
          type: integer

paths:
  /animations:
    get:
      summary: Gets all animations available
      description: Returns a list containing all animations.
      tags: [Animations]
      responses:
        200:
          description: A list of Animations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animation'
        400:
          $ref: '#/components/responses/Error400Response'
        404:
          $ref: '#/components/responses/Error404Response'
        500:
          $ref: '#/components/responses/Error500Response'
    delete:
      summary: Stops the current animation
      description: Stops the current animation on the wall
      tags: [Animations]
      parameters:
        - $ref: '#/components/parameters/animationIdParameter_path'
      responses:
        201:
          description: "Playing the selected animation"
        400:
          $ref: '#/components/responses/Error400Response'
        404:
          $ref: '#/components/responses/Error404Response'
        500:
          $ref: '#/components/responses/Error500Response'
  /animations/{animationId}:
    post:
      summary: Plays an animation
      description: Plays the selected animation on the wall
      tags: [Animations]
      parameters:
        - $ref: '#/components/parameters/animationIdParameter_path'
        - $ref: '#/components/parameters/animationColorsParameter_query'
        - $ref: '#/components/parameters/animationStringsParameter_query'
        - $ref: '#/components/parameters/animationValuesIntegerParameter_query'
      responses:
        200:
          description: "Stopped the animation"
        400:
          $ref: '#/components/responses/Error400Response'
        404:
          $ref: '#/components/responses/Error404Response'
        500:
          $ref: '#/components/responses/Error500Response'
